PREFIX ?= /usr/local/bin
VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo "unknown")
VERSION_FILE = Sources/HTML2ImgCLI/version.swift

build: $(VERSION_FILE)
	swift build -c release

build-universal: clean $(VERSION_FILE)
	swift build -c release --arch x86_64
	cp .build/release/html2img .build/html2img-x86_64
	swift build -c release --arch arm64
	cp .build/release/html2img .build/html2img-arm64
	mkdir -p .build/universal
	lipo -create -output .build/universal/html2img .build/html2img-x86_64 .build/html2img-arm64

install: build
	install .build/release/html2img $(PREFIX)/html2img

install-universal: build-universal
	install .build/universal/html2img $(PREFIX)/html2img

uninstall:
	rm -f $(PREFIX)/html2img

test:
	swift test

clean:
	swift package clean

release: test build
	@echo "Built html2img $(VERSION) at .build/release/html2img"

tag:
	@if [ -n "$$(git status --porcelain)" ]; then echo "Error: working tree dirty"; exit 1; fi
	@if [ -z "$(TAG)" ]; then echo "Usage: make tag TAG=v0.x.0"; exit 1; fi
	git tag -a $(TAG) -m "$(TAG)"
	@echo "Tagged $(TAG). Run 'make release' to build, then 'git push origin $(TAG)' to publish."

$(VERSION_FILE): Makefile
	@echo "// Auto-generated by Makefile — do not edit manually." > $(VERSION_FILE)
	@echo "let html2imgVersion = \"$(VERSION)\"" >> $(VERSION_FILE)

.PHONY: build build-universal install install-universal uninstall test clean release tag
